### ISSUE TITLE
Feature Request: Refresh token on expiry (or quit!)

### ISSUE THREAD

**Issue by nielm** [GoogleCloudPlatform/cloud-run-proxy#18]
The requested token expires after 1hr normally. The tool knows this expire time, but will continue running. 

If the tool could refresh the token automatically on expiry, or quit so that it could be relaunched automatically, then this would be a great additional feature.

Workaround: 
```bash
while true ; do 
   ./cloud-run-proxy \
       -host "${SERVER_HOST}"  \
       -bind "127.0.0.1:8001" \
       -server-up-time 50m
done &
```

**Comment by sethvargo** [comment]
Hi @nielm 

Thank you for opening an issue. The workaround you provided is the best option. Not all tokens are refreshable or inspectable by the client, and Go doesn't offer a great way to signal shutdown from inside the proxy.
