### ISSUE TITLE
Support/FR: Allow `-bind` usage on `gcloud run services proxy` command

### ISSUE THREAD

**Issue by pataquets** [GoogleCloudPlatform/cloud-run-proxy#42]
GCloud SDK's CLI command `gcloud run services proxy` does not provide an equivalent `-bind` switch. To listen on `0.0.0.0`, for example.

**Comment by sethvargo** [comment]
Hi @pataquets - this component is for the cloud-run-proxy binary. It's used in the gcloud tool, but it's a standalone binary and already supports the `-bind` flag. If you want to request a feature for supporting it in gcloud, please file a feature request: https://cloud.google.com/sdk/docs/getting-support
