### ISSUE TITLE
Persistent Authentication

### ISSUE THREAD

**Issue by alexwilson1** [GoogleCloudPlatform/cloud-run-proxy#43]
Each day this prompts us with the following message:

```
ERROR: (gcloud.beta.run.services.proxy) There was a problem refreshing your current auth tokens: Reauthentication failed. cannot prompt during non-interactive execution.
Please run:

  $ gcloud auth login

to obtain new credentials.

If you have already logged in with a different account, run:

  $ gcloud config set account ACCOUNT

to select an already authenticated account to use.
```

We then use `gcloud auth login` which opens the browser auth flow and it works again until the next morning.

We think this may be due to organizational security policy set at https://admin.google.com/ac/security/reauth/admin-tools (re-authenticate after x hours) but cannot find a way to add this cloud run proxy as a trusted application as described [here](https://apps.google.com/supportwidget/articlehome?hl=en&article_url=https%3A%2F%2Fsupport.google.com%2Fa%2Fanswer%2F9368756%3Fhl%3Den&assistant_id=generic-unu&product_context=9368756&product_name=UnuFlow&trigger_context=a).

Any pointers would be appreciated. We want to keep the security policy but ensure we don't have to re-authenticate for Cloud Run Proxy.

**Comment by sethvargo** [comment]
The re-authentication policy requires you to re-authenticate every XX hours as defined. There's nothing we can do to avoid that.

**Comment by sethvargo** [comment]
Cloud Run Proxy _does_ use ADC. On your local machine, it's pulling ADC from gcloud, which requires the rapt.
